version: 2
updates:
# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/client'
  schedule:
    interval: weekly
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - sundowndev
  assignees:
    - sundowndev
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
# Enable version updates for Go modules
- package-ecosystem: gomod
  directory: '/'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - sundowndev
  assignees:
    - sundowndev
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
# Fetch and update latest `github-actions` pkgs
- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - sundowndev
  assignees:
    - sundowndev
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
# Enable version updates for Docker
- package-ecosystem: "docker"
  # Look for a `Dockerfile` in the `root` directory
  directory: "/"
  # Check for updates once a week
  schedule:
    interval: "weekly"
